// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Gibbs_chain_C
NumericMatrix Gibbs_chain_C(double a, double b, int n, int N, int burn, int x0, double y0);
RcppExport SEXP _SA24168406_Gibbs_chain_C(SEXP aSEXP, SEXP bSEXP, SEXP nSEXP, SEXP NSEXP, SEXP burnSEXP, SEXP x0SEXP, SEXP y0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< int >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< double >::type y0(y0SEXP);
    rcpp_result_gen = Rcpp::wrap(Gibbs_chain_C(a, b, n, N, burn, x0, y0));
    return rcpp_result_gen;
END_RCPP
}
// My_stratified_samplingC
List My_stratified_samplingC(DataFrame data, const List& samplesPerCategory);
RcppExport SEXP _SA24168406_My_stratified_samplingC(SEXP dataSEXP, SEXP samplesPerCategorySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const List& >::type samplesPerCategory(samplesPerCategorySEXP);
    rcpp_result_gen = Rcpp::wrap(My_stratified_samplingC(data, samplesPerCategory));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SA24168406_Gibbs_chain_C", (DL_FUNC) &_SA24168406_Gibbs_chain_C, 7},
    {"_SA24168406_My_stratified_samplingC", (DL_FUNC) &_SA24168406_My_stratified_samplingC, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_SA24168406(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
