# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name Gibbs_chain_C
#' @title A Gibbs sampler function using Rcpp
#' @description Samples are drawn according to the idea of Gibbs sampler using Rcpp
#' @useDynLib SA24168406
#' @param a one of the parameters of binary density
#' @param b one of the parameters of binary density
#' @param n one of the parameters of binary density
#' @param N the number of samples generated
#' @param burn the number of samples discarded
#' @param x0 the initial x-value
#' @param y0 the initial y-value
#' @return A NumericMatrix of the samples \code{n}
#' @examples
#' \dontrun{
#'     set.seed(12345)
#'     N <- 1e4
#'     burn <- 1000
#'     a <- 2
#'     b <- 4
#'     n <- 16
#'     x0 <- sample(0:n,1)
#'     y0 <- runif(1)
#'     xC <- Gibbs_chain_C(a, b, n, N, burn, x0, y0)
#' }
#' @export
NULL

Gibbs_chain_C <- function(a, b, n, N, burn, x0, y0) {
    .Call('_SA24168406_Gibbs_chain_C', PACKAGE = 'SA24168406', a, b, n, N, burn, x0, y0)
}

#' @name My_stratified_samplingC
#' @title A Stratified sampling function using Rcpp
#' @description Samples are drawn according to the idea of stratified sampling using Rcpp
#' @useDynLib SA24168406
#' @param data The data that contains the id, category, and value columns
#' @param samplesPerCategory The number of samples for each category
#' @return A list of the sampling results including id and category \code{n}
#' @examples
#' \dontrun{
#'     data <- data.frame(id = 1:9, category = rep(c("A", "B", "C"), each = 3), value = rnorm(9))
#'     samples_per_category <- list(A = 1, B = 2, C = 1)
#'     sampled_data <- My_stratified_samplingC(data, samples_per_category)
#' }
#' @export
NULL

My_stratified_samplingC <- function(data, samplesPerCategory) {
    .Call('_SA24168406_My_stratified_samplingC', PACKAGE = 'SA24168406', data, samplesPerCategory)
}

